---
- name: "Copy backend tar.gz file and unzipping it"
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: "installing dependencies"
  become: yes
  npm:
    path: /home/ubuntu/backend

- name: "fixing dependencies"
  become: yes
  shell: npm audit fix --audit-level=critical --force
  args:
    chdir: /home/ubuntu/backend

- name: "building packages"
  become: yes
  shell: npm run build
  args:
    chdir: /home/ubuntu/backend

- name: "run migration"
  become: yes
  shell: npm run migrations
  args:
    chdir: /home/ubuntu/backend

- name: "initialize pm2"
  become: yes
  shell: pm2 ls
  args:
    chdir: /home/ubuntu/backend

- name: "start pm2"
  become: yes
  shell: pm2 start --name "backend" npm -- start
  args:
    chdir: /home/ubuntu/backend