---
- name: "Copy backend tar.gz file and unzipping it"
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: "installing dependencies"
  become: yes
  shell: |
    cd /home/ubuntu/backend
    ls
    sudo npm cache clean -f
    sudo npm install -g n
    sudo n stable
    PATH="$PATH"
    npm i
    npm run build

- name: "run migration"
  become: yes
  shell: cd /home/ubuntu/backend && npm run migrations

- name: "initialize pm2"
  become: yes
  shell: cd /home/ubuntu/backend && pm2 ls

- name: "start pm2"
  become: yes
  shell: |
    cd /home/ubuntu/backend && pm2 start --name "backend" npm -- start
    sleep 120s