# This file will reside under alertmanager.
# You will need to get the webhook url for your slack, follow instruction mentioned on below link to get it:
# https://grafana.com/blog/2020/02/25/step-by-step-guide-to-setting-up-prometheus-alertmanager-with-slack-pagerduty-and-gmail/

global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#cicd'
      send_resolved: true